name: Prestige
on:
  push:
    branches: [ prestige ]
jobs:
  prestige:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn && yarn sign
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: lexogrine_hud_2.3.0.signed.zip
