name: build
on:
  push:
    branches: [ classic ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn && yarn sign
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: UC_Classic
          path: build/
